Repository ivadomed/ivadomed, pull requests merged in 2020-08, with the labels that each got.

#390 Added special case for Centercrop in visualize transforms
  ivadomed/scripts/visualize_transforms.py
Labels: Ready for review

#385 Create coverage and improve testing
  .coveragerc
  .github/workflows/run_tests.yml
  README.md
  ivadomed/loader/loader.py
  ivadomed/training.py
  testing/ivado_test.py
  testing/test_HeMIS.py
  testing/test_adaptative.py
  testing/test_bounding_box.py
  testing/test_inference.py
  testing/test_losses.py
  testing/test_metrics.py
  testing/test_model.py
  testing/test_onnx.py
  testing/test_orientation.py
  testing/test_postprocessing.py
  testing/test_sampler.py
  testing/test_script.py
  testing/test_segment_volume.py
  testing/test_sliceFilter.py
  testing/test_training_time.py
  testing/test_transfer_learning.py
  testing_data/model_config.json
Labels: draft

#400 Classif documentation
  docs/source/comparison_other_projects_table.csv
  docs/source/models.rst
  ivadomed/models.py
Labels: documentation

#424 Missing {} in automate_training example
  ivadomed/scripts/automate_training.py
Labels: documentation
