Repository ivadomed/ivadomed, pull requests merged in 2020-11, with the labels that each got.

#497 Refactor utils.py
  dev/class_balance.py
  dev/metadata_config.py
  dev/plot_cluster_metadata.py
  docs/source/api_ref.rst
  docs/source/conf.py
  docs/source/configuration_file.rst
  ivadomed/config_manager.py
  ivadomed/inference.py
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/maths.py
  ivadomed/metrics.py
  ivadomed/mixup.py
  ivadomed/object_detection/utils.py
  ivadomed/preprocessing.py
  ivadomed/scripts/prepare_dataset_vertebral_labeling.py
  ivadomed/testing.py
  ivadomed/training.py
  ivadomed/uncertainty.py
  ivadomed/utils.py
  ivadomed/visualize.py
  testing/test_HeMIS.py
  testing/test_adaptative.py
  testing/test_mixup.py
  testing/test_onnx.py
  testing/test_orientation.py
  testing/test_rgb.py
  testing/test_script.py
  testing/test_segment_volume.py
  testing/test_tensorboard_save.py
Labels: refactoring

#491 FiLM for 3D Unet
  docs/source/architectures.rst
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_default.json
  ivadomed/config/config_tumorSeg.json
  ivadomed/config_manager.py
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/loader/loader.py
  ivadomed/main.py
  ivadomed/models.py
  ivadomed/testing.py
  ivadomed/training.py
  ivadomed/utils.py
  testing/test_bounding_box.py
  testing/test_inference.py
  testing/test_model.py
  testing/test_onnx.py
  testing/test_orientation.py
  testing/test_script.py
  testing/test_segment_volume.py
  testing/test_training_time.py
Labels: feature

#498 Training without test set
  .gitignore
  docs/source/configuration_file.rst
  ivadomed/config_manager.py
  ivadomed/inference.py
  ivadomed/loader/film.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/utils.py
  testing/test_script.py
  testing/test_split_dataset.py
Labels: feature

#502 JOSS submission
  docs/source/index.rst
  docs/source/use_cases.rst
  paper.bib
  paper.md
Labels: documentation

#503 Create sample to balance metadata
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_default.json
  ivadomed/config_manager.py
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/training.py
  testing/test_script.py
Labels: feature

#522 Support multiclass if first class missing
  ivadomed/evaluation.py
  ivadomed/loader/loader.py
  ivadomed/testing.py
Labels: bug

#524 Multiclass and multichannel support for segment volume
  ivadomed/inference.py
  ivadomed/loader/loader.py
  ivadomed/main.py
  ivadomed/object_detection/utils.py
  testing/test_script.py
  testing/test_segment_volume.py
Labels: enhancement
