Repository ivadomed/ivadomed, pull requests merged in 2020-09, with the labels that each got.

#425 Updating documentation
  .readthedocs.yml
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/data.rst
  docs/source/scripts.rst
  images/detailed_results.csv
  images/df_compare.csv
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/compare_models.py
  ivadomed/scripts/convert_to_onnx.py
  ivadomed/scripts/download_data.py
  ivadomed/scripts/extract_small_dataset.py
  ivadomed/scripts/prepare_dataset_vertebral_labeling.py
  ivadomed/scripts/training_curve.py
  ivadomed/scripts/visualize_transforms.py
  setup.py
Labels: Ready for review, documentation

#436 typo in link fixed
  docs/source/data.rst
Labels: documentation

#449 Al/fixes prior release
  ivadomed/models.py
  ivadomed/training.py
  ivadomed/utils.py
Labels: bug

#447 Retrain model without resetting weights
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_classification.json
  ivadomed/config/config_sctTesting.json
  ivadomed/config/config_small.json
  ivadomed/config/config_spineGeHemis.json
  ivadomed/config/config_tumorSeg.json
  ivadomed/config/config_vertebral_labeling.json
  ivadomed/models.py
  ivadomed/training.py
Labels: enhancement

#453 fix run_test gpu assignation
  ivadomed/scripts/automate_training.py
Labels: bug

#458 Custom final activation
  ivadomed/models.py
Labels: enhancement

#460 Use custom data for film
  docs/source/configuration_file.rst
  ivadomed/loader/film.py
  ivadomed/loader/loader.py
  ivadomed/training.py
  testing/test_orientation.py
Labels: feature
