Repository ivadomed/ivadomed, pull requests merged in 2020-12, with the labels that each got.

#534 Select subjects for training based on metadata
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_default.json
  ivadomed/loader/utils.py
  ivadomed/main.py
Labels: feature

#547 Fix missing attribute softmax
  ivadomed/models.py
Labels: bug

#562 Handling python version for install
  README.md
  docs/source/installation.rst
Labels: documentation

#560 Updating comparison table after review
  docs/source/documentation.csv
  docs/source/general_overview.csv
  docs/source/model_evaluation.csv
  docs/source/pipeline_features.csv
  docs/source/purpose.rst
Labels: documentation

#546 Random sampling of expert annotations
  docs/source/configuration_file.rst
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/transforms.py
Labels: enhancement

#565 Add issue/PR templates + root-level community guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  docs/source/contributing.rst
Labels: documentation

#569 Save config file before training
  ivadomed/main.py
Labels: enhancement

#549 Apply bounding box safety factor in segment volume
  ivadomed/inference.py
  ivadomed/object_detection/utils.py
Labels: enhancement

#570 Remove small for multiclass
  docs/source/configuration_file.rst
  ivadomed/inference.py
  ivadomed/postprocessing.py
Labels: enhancement

#571 Add a Help section to the Sphinx docs
  docs/source/help.rst
  docs/source/index.rst
Labels: documentation

#578 Make usage clearer
  docs/source/usage.rst
Labels: documentation

#582 Load 2D GT slice as uint if not soft training
  ivadomed/loader/loader.py
Labels: bug

#586 Automate_training: fix bug for multiple parameters
  ivadomed/scripts/automate_training.py
Labels: bug

#584 Add tests for create_bids_dataframe function
  dev/df_new_loader.py
  ivadomed/loader/utils.py
  ivadomed/scripts/download_data.py
  requirements.txt
  testing/unit_tests/test_loader.py
Labels: testing
