Repository ivadomed/ivadomed, pull requests merged in 2020-10, with the labels that each got.

#459 Uncertainty as post-processing step
  ivadomed/config/config.json
  ivadomed/config/config_classification.json
  ivadomed/config/config_sctTesting.json
  ivadomed/config/config_small.json
  ivadomed/config/config_spineGeHemis.json
  ivadomed/config/config_tumorSeg.json
  ivadomed/config/config_vertebral_labeling.json
  ivadomed/evaluation.py
  ivadomed/main.py
  ivadomed/testing.py
  ivadomed/utils.py
Labels: feature

#467 Refactoring: Changing print and exit to raise error
  ivadomed/loader/adaptative.py
  ivadomed/models.py
  ivadomed/scripts/visualize_transforms.py
  ivadomed/testing.py
  ivadomed/training.py
  ivadomed/transforms.py
Labels: enhancement

#472 Adapt all metrics to multiclass predictions
  ivadomed/evaluation.py
  ivadomed/testing.py
Labels: bug

#477 Improving documentation
  docs/source/architectures.rst
  docs/source/comparison_other_projects_table.csv
  docs/source/configuration_file.rst
  docs/source/contributing.rst
  docs/source/data.rst
  docs/source/index.rst
  docs/source/license.rst
  docs/source/pretrained_models.rst
  docs/source/purpose.rst
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  docs/source/usage.rst
  images/1920px-BIDS_Logo.png
  ivadomed/losses.py
  ivadomed/main.py
  ivadomed/models.py
  ivadomed/scripts/download_data.py
Labels: documentation

#481 Version format
  ivadomed/version.txt
Labels: bug

#485 Added reference to arXiv citation
  docs/source/index.rst
Labels: documentation

#488 Fix missing version.txt in wheels package
  MANIFEST.in
  setup.py
Labels: bug

#484 Configuration File Manager
  dev/class_balance.py
  dev/filtering_lesion.py
  dev/metadata_config.py
  dev/plot_cluster_metadata.py
  dev/plot_film_parameters.py
  dev/reproducibility.py
  dev/target_size.py
  ivadomed/__init__.py
  ivadomed/config/config_default.json
  ivadomed/config_manager.py
  ivadomed/main.py
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/visualize_transforms.py
  ivadomed/utils.py
  testing/test_script.py
Labels: enhancement

#486 Option to override postprocessing in segment volume
  ivadomed/utils.py
  testing/test_script.py
Labels: enhancement

#500 set h5py version in requirements.txt
  requirements.txt
Labels: bug, dependencies
