Repository ivadomed/ivadomed, pull requests merged in 2021-06, with the labels that each got.

#782 Add image reconstruction from 2D patches
  ivadomed/config/config_new_loader.json
  ivadomed/inference.py
  ivadomed/loader/loader.py
  ivadomed/testing.py
  testing/functional_tests/test_segment_volume.py
Labels: feature

#806 Fix bug in loader for multiple raters
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  testing/unit_tests/test_loader.py
Labels: bug, testing

#820 Add missing "-r" flags to installation.rst
  docs/source/installation.rst
Labels: bug, documentation

#813 New loader: Load PNG/TIF/JPG microscopy files as Nibabel objects
  docs/source/configuration_file.rst
  ivadomed/config/config_new_loader.json
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/testing.py
  testing/unit_tests/test_loader.py
Labels: enhancement

#837 Fix multiclass evaluation bug
  ivadomed/config/config_new_loader.json
  ivadomed/evaluation.py
Labels: bug

#835 Fix last slice missing in testing bug
  ivadomed/config/config_new_loader.json
  ivadomed/testing.py
  testing/unit_tests/test_testing.py
Labels: bug

#838 Update config_bids.json following changes in microscopy BEP
  ivadomed/config/config_bids.json
Labels: refactoring
