Repository ivadomed/ivadomed, pull requests merged in 2021-11, with the labels that each got.

#949 Update scripts in `dev/prepare_data` to use new SCT config syntax (`.yml`)
  dev/prepare_data/README.md
  dev/prepare_data/check_input_files.sh
  dev/prepare_data/clean.sh
  dev/prepare_data/config_template.yml
  dev/prepare_data/delete_tmp_files.sh
  dev/prepare_data/final_qc.sh
  dev/prepare_data/parameters_template.sh
  dev/prepare_data/prepare_data.sh
Labels: bug

#978 Fix resample axis order in documentation
  docs/source/configuration_file.rst
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  docs/source/tutorials/uncertainty.rst
  ivadomed/config/config.json
  ivadomed/config/config_classification.json
  ivadomed/config/config_microscopy.json
  ivadomed/config/config_sctTesting.json
  ivadomed/config/config_small.json
  ivadomed/config/config_spineGeHemis.json
  ivadomed/config/config_tumorSeg.json
Labels: documentation

#758 Standardize Header Handling when creating new nibabel object
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/postprocessing.py
  ivadomed/preprocessing.py
  ivadomed/scripts/download_data.py
  ivadomed/training.py
  ivadomed/uncertainty.py
  ivadomed/visualize.py
Labels: priority:medium

#819 Make ivadomed be compatible with python3.9 and PyTorch 1.8
  .github/workflows/run_tests.yml
  ivadomed/loader/adaptative.py
  ivadomed/scripts/download_data.py
  requirements.txt
  requirements_common.txt
  setup.py
Labels: bug, enhancement, documentation, CI

#922 Fixes object detection path in cascaded architecture tutorial
  docs/source/tutorials/cascaded_architecture.rst
Labels: documentation

#901 pathlib for tests
  testing/common_testing_util.py
  testing/functional_tests/t_template.py
  testing/functional_tests/t_utils.py
  testing/functional_tests/test_automate_training.py
  testing/functional_tests/test_compare_models.py
  testing/functional_tests/test_convert_to_onnx.py
  testing/functional_tests/test_download_data.py
  testing/functional_tests/test_extract_small_dataset.py
  testing/functional_tests/test_prepare_dataset_vertebral_labelling.py
  testing/functional_tests/test_segment_volume.py
  testing/functional_tests/test_training_curve.py
  testing/functional_tests/test_visualize_transforms.py
  testing/unit_tests/t_template.py
  testing/unit_tests/t_utils.py
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_metrics.py
  testing/unit_tests/test_mixup.py
  testing/unit_tests/test_onnx.py
  testing/unit_tests/test_postprocessing.py
  testing/unit_tests/test_rgb.py
  testing/unit_tests/test_split_dataset.py
  testing/unit_tests/test_tensorboard_save.py
  testing/unit_tests/test_testing.py
  testing/unit_tests/test_transfer_learning.py
Labels: refactoring

#987 Pin PyParsing version to be compatible with pip 20
  requirements_common.txt
Labels: bug

#984 Fully Remove HeMIS model, Adaptive and h5py/HDF5
  ivadomed/loader/adaptative.py
  ivadomed/loader/bids_dataframe.py
  ivadomed/loader/loader.py
  ivadomed/training.py
  requirements_common.txt
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
Labels: refactoring, maintenance, architecture

#988 Minor modifications to the documentation for tutorial 3
  docs/source/tutorials/uncertainty.rst
Labels: documentation

#969 Update installation instruction to fit recent CUDA11 and torch 1.8+ push
  docs/source/api_ref.rst
  docs/source/conf.py
  docs/source/installation.rst
  environment.yml
  requirements_dev.txt
Labels: documentation

#992 Update Tutorial 1/2/3 and readme.md to fix minor display issues
  README.md
  docs/source/tutorials/cascaded_architecture.rst
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  docs/source/tutorials/uncertainty.rst
Labels: documentation

#982 Apply transforms on 2D patches
  ivadomed/loader/mri2d_segmentation_dataset.py
Labels: enhancement
