Repository ivadomed/ivadomed, pull requests merged in 2021-12, with the labels that each got.

#995 Add forced indexation of "micr" datatype
  ivadomed/config/config_bids.json
  ivadomed/loader/bids_dataframe.py
Labels: enhancement

#946 Use keywords for the rest of the files
  ivadomed/config_manager.py
  ivadomed/inference.py
  ivadomed/keywords.py
  ivadomed/loader/bids_dataset.py
  ivadomed/loader/film.py
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
  ivadomed/loader/segmentation_pair.py
  ivadomed/main.py
  ivadomed/object_detection/utils.py
  ivadomed/scripts/visualize_transforms.py
  ivadomed/testing.py
  ivadomed/training.py
  ivadomed/transforms.py
  ivadomed/utils.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_transforms.py
Labels: refactoring

#998 Experimental incorporation of tutorial jupyter notebooks open in Colab path
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  docs/source/tutorials/uncertainty.rst
  testing/tutorials/readme.md
  testing/tutorials/tutorial_1_2d_segmentation_unet.ipynb
  testing/tutorials/tutorial_3_uncertainty_estimation.ipynb
Labels: documentation, testing

#1021 Typo fix for URL that is bricking the Colab link
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
Labels: documentation

#1015 Implementation of Random Gamma Contrast Augmentation
  docs/source/configuration_file.rst
  ivadomed/keywords.py
  ivadomed/transforms.py
Labels: feature, Ready for review, priority:high

#1033 Implementation of Random Bias Field Augmentation
  docs/source/configuration_file.rst
  ivadomed/keywords.py
  ivadomed/transforms.py
  requirements_common.txt
Labels: feature, Ready for review

#1034 Implementation of Random Blur Augmentation
  docs/source/configuration_file.rst
  ivadomed/keywords.py
  ivadomed/transforms.py
Labels: feature, Ready for review

#1024 Fix pixel size keyword in run_segment_command
  ivadomed/main.py
Labels: bug

#1028 Removed one child-headings for clarity
  docs/source/configuration_file.rst
Labels: documentation
