Repository ivadomed/ivadomed, pull requests merged in 2021-07, with the labels that each got.

#828 Extracted Loader Classes into separate files
  dev/class_balance.py
  dev/metadata_config.py
  dev/plot_cluster_metadata.py
  ivadomed/inference.py
  ivadomed/loader/adaptative.py
  ivadomed/loader/bids3d_dataset.py
  ivadomed/loader/bids_dataset.py
  ivadomed/loader/loader.py
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
  ivadomed/loader/segmentation_pair.py
  ivadomed/loader/utils.py
  ivadomed/object_detection/utils.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_orientation.py
Labels: refactoring

#845 Remove `anaconda` from explicit dependencies
  environment.yml
Labels: bug, dependencies, installation

#834 Add the inference steps for PNG/TIF microscopy data
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/loader/loader.py
  ivadomed/loader/segmentation_pair.py
  ivadomed/main.py
  ivadomed/testing.py
  testing/unit_tests/test_testing.py
Labels: enhancement

#847 Installation instruction steps explicity recommended for MacOS but not Linux
  docs/source/installation.rst
Labels: Ready for review, documentation

#793 Speed up IvadoMed Import Speed
  ivadomed/utils.py
Labels: enhancement

#842 Clarified step 2 for pytorch/torchvision
  docs/source/installation.rst
Labels: documentation

#850 Add microscopy config file
  ivadomed/config/config_microscopy.json
  ivadomed/inference.py
  ivadomed/main.py
Labels: enhancement

#854 `utils.py`: Only raise ArgParseException for non-zero SystemExits
  ivadomed/utils.py
Labels: bug
