Repository ivadomed/ivadomed, pull requests merged in 2021-02, with the labels that each got.

#652 Externalize command, log_directory, and bids_path fields from JSON config files to CLI
  dev/class_balance.py
  dev/df_new_loader.py
  dev/filtering_lesion.py
  dev/metadata_config.py
  dev/plot_cluster_metadata.py
  dev/plot_film_parameters.py
  dev/reproducibility.py
  dev/target_size.py
  docs/source/configuration_file.rst
  docs/source/pretrained_models.rst
  docs/source/tutorials/cascaded_architecture.rst
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  docs/source/tutorials/uncertainty.rst
  docs/source/usage.rst
  images/detailed_results.csv
  images/df_compare.csv
  ivadomed/config/config.json
  ivadomed/config/config_classification.json
  ivadomed/config/config_default.json
  ivadomed/config/config_new_loader.json
  ivadomed/config/config_sctTesting.json
  ivadomed/config/config_small.json
  ivadomed/config/config_spineGeHemis.json
  ivadomed/config/config_tumorSeg.json
  ivadomed/config/config_vertebral_labeling.json
  ivadomed/evaluation.py
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/object_detection/utils.py
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/compare_models.py
  ivadomed/scripts/download_data.py
  ivadomed/scripts/training_curve.py
  ivadomed/testing.py
  ivadomed/training.py
  ivadomed/utils.py
  ivadomed/visualize.py
  testing/functional_tests/test_automate_training.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_inference.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_split_dataset.py
  testing/unit_tests/test_training_time.py
Labels: card:DESIGN_DISCUSSION, enhancement

#668 Add new keys config manager
  ivadomed/config_manager.py
  ivadomed/utils.py
Labels: enhancement

#677 Adding Zenodo DOI
  README.md
Labels: documentation

#612 Clarified doc on config file and fixed few typos/formatting issues
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_default.json
Labels: card:DESIGN_DISCUSSION, documentation

#682 Add pre-commit hooks to limit file size to 500KB
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  docs/source/installation.rst
  requirements.txt
  setup.py
Labels: CI, enhancement, priority:medium

#683 Add DOI JOSS
  README.md
  docs/source/index.rst
Labels: documentation

#684 Merged participants.tsv file saving bug correction
  ivadomed/evaluation.py
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
Labels: bug

#661 Allow for non-dictionary hyperparameters in automate_training
  docs/source/index.rst
  docs/source/scripts.rst
  docs/source/tutorials/automate_training.rst
  docs/source/tutorials/detailed_results.csv
  docs/source/tutorials/uncertainty.rst
  docs/source/usage.rst
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/hyperparameters_training.json
  testing/functional_tests/test_automate_training.py
  testing/unit_tests/test_automate_training.py
Labels: bug, documentation, enhancement

#688 Multiclass ignored during inference if n_input and n_output are different
  ivadomed/inference.py
Labels: bug

#687 New loader: input from multiple BIDS datasets
  ivadomed/loader/utils.py
  testing/unit_tests/test_loader.py
Labels: enhancement

#690 Dynamically write dataset_description.json file to suppress pybids warning
  ivadomed/loader/utils.py
Labels: bug

#692 Extract various functionalities of run_command into helper functions
  ivadomed/main.py
Labels: refactoring
