Repository ivadomed/ivadomed, pull requests merged in 2021-05, with the labels that each got.

#769 Hot patch a misconfigured Pytest Param that could fail local running of test_load_dataset_2d_png in venv
  testing/unit_tests/test_loader.py
Labels: CI, priority:medium, testing

#767 Migrate test_segment_volume.py from unit_tests to functional_tests
  testing/functional_tests/test_segment_volume.py
Labels: testing

#771 Update documentation with the solution to failing test_adaptive.py on MacOS
  docs/source/installation.rst
Labels: documentation, testing

#763 New loader: Generate 2D patches
  docs/source/configuration_file.rst
  ivadomed/config/config_new_loader.json
  ivadomed/loader/loader.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_orientation.py
Labels: feature

#776 Exclude testing directory in coveralls
  .github/workflows/run_tests.yml
Labels: CI, testing

#779 Update one class segmentation tutorial's output and segmentation image
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
Labels: documentation

#760 Add sha256 for training data
  ivadomed/main.py
  ivadomed/utils.py
  testing/functional_tests/t_utils.py
  testing/functional_tests/test_automate_training.py
  testing/unit_tests/test_automate_training.py
Labels: feature

#765 Refactoring: BidsDataset __init__ reduce complexity
  ivadomed/loader/loader.py
  testing/unit_tests/test_loader.py
Labels: refactoring

#791 Refactor segment_volume to reduce complexity
  ivadomed/inference.py
Labels: refactoring

#805 Update test_segment_volume_2d to use ROI
  testing/functional_tests/test_segment_volume.py
Labels: testing

#804 Hot patch to address Inference issue #803
  ivadomed/inference.py
  testing/functional_tests/test_segment_volume.py
Labels: bug, deep learning, priority:high

#764 Add logging for functions in main.py
  docs/source/configuration_file.rst
  ivadomed/config/config_default.json
  ivadomed/config_manager.py
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/loader/adaptative.py
  ivadomed/loader/film.py
  ivadomed/loader/loader.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/object_detection/utils.py
  ivadomed/postprocessing.py
  ivadomed/testing.py
  ivadomed/training.py
  ivadomed/transforms.py
  ivadomed/utils.py
  ivadomed/visualize.py
  requirements.txt
Labels: enhancement

#757 Improve current GitHub Action CI with multi OS support
  .github/workflows/pre-commit.yml
  .github/workflows/run_tests.yml
  .gitignore
  .readthedocs.yml
  docs/source/installation.rst
  environment.yml
  ivadomed/scripts/automate_training.py
  requirements.txt
  requirements_common.txt
  requirements_dev.txt
  requirements_gpu.txt
  setup.py
  testing/functional_tests/test_automate_training.py
Labels: CI, priority:medium, testing

#811 Remove force continuous run which gave false positive in GitHub CI causing Issue 810
  .github/workflows/run_tests.yml
Labels: priority:high
