Repository ivadomed/ivadomed, pull requests merged in 2021-01, with the labels that each got.

#606 Fix pandas typecast issue in test_split_dataset.py
  ivadomed/loader/utils.py
  testing/unit_tests/test_split_dataset.py
Labels: bug

#609 Indicate folder created after running ivadomed_download_data
  ivadomed/scripts/download_data.py
Labels: enhancement

#616 Update PyTorch Ref
  docs/source/index.rst
  paper.bib
Labels: documentation

#610 Small clarifications and typos fixes in the Unet tutorial
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
Labels: documentation

#618 Add DeepReg to comparison table
  docs/source/comparison_other_projects_table.csv
  docs/source/purpose.rst
Labels: documentation

#603 Specify Python version in setup.py
  setup.py
Labels: enhancement

#622 Add the Twitter badge
  README.md
Labels: documentation

#597 Made the BIDS example more general for the audience
  docs/source/data.rst
Labels: documentation

#602 Make sure test_HeMIS runs tests in order
  testing/unit_tests/test_HeMIS.py
Labels: bug

#625 Add documentation on packaged model format
  docs/source/pretrained_models.rst
  ivadomed/config/config.json
  ivadomed/config/config_default.json
Labels: documentation

#623 AnimatedGIf import and documentation
  ivadomed/main.py
  ivadomed/training.py
Labels: bug

#634 Remove test_script and ivado_functional_test files
  ivadomed/scripts/download_data.py
  testing/functional_tests/ivado_functional_test.py
  testing/functional_tests/test_script.py
Labels: refactoring

#626 Add a README for the Sphinx docs
  docs/README.md
Labels: documentation, enhancement

#636 Unit Test cleanup
  .github/workflows/run_tests.yml
  ivadomed/loader/utils.py
  ivadomed/losses.py
  ivadomed/scripts/download_data.py
  testing/unit_tests/ivado_test.py
  testing/unit_tests/t_utils.py
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_inference.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_losses.py
  testing/unit_tests/test_metrics.py
  testing/unit_tests/test_mixup.py
  testing/unit_tests/test_model.py
  testing/unit_tests/test_onnx.py
  testing/unit_tests/test_orientation.py
  testing/unit_tests/test_postprocessing.py
  testing/unit_tests/test_rgb.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_segment_volume.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_split_dataset.py
  testing/unit_tests/test_tensorboard_save.py
  testing/unit_tests/test_training_time.py
  testing/unit_tests/test_transfer_learning.py
  testing/unit_tests/test_transforms.py
Labels: enhancement, refactoring

#594 Add new filter to SliceFilter class
  docs/source/configuration_file.rst
  ivadomed/loader/utils.py
Labels: enhancement

#642 Fix store film params
  ivadomed/training.py
Labels: bug

#591 New loader: Adapt splitting methods
  dev/df_new_loader.py
  ivadomed/config/config_new_loader.json
  ivadomed/loader/utils.py
  testing/unit_tests/test_loader.py
Labels: enhancement

#644 Standardize the gpu ID argument
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_classification.json
  ivadomed/config/config_default.json
  ivadomed/config/config_new_loader.json
  ivadomed/config/config_sctTesting.json
  ivadomed/config/config_small.json
  ivadomed/config/config_spineGeHemis.json
  ivadomed/config/config_tumorSeg.json
  ivadomed/config/config_vertebral_labeling.json
  ivadomed/inference.py
  ivadomed/main.py
  ivadomed/object_detection/utils.py
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/convert_to_onnx.py
  ivadomed/scripts/download_data.py
  ivadomed/utils.py
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
  testing/unit_tests/test_inference.py
  testing/unit_tests/test_orientation.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_training_time.py
Labels: refactoring

#641 Add metavar to parser
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/compare_models.py
  ivadomed/scripts/convert_to_onnx.py
  ivadomed/scripts/download_data.py
  ivadomed/scripts/extract_small_dataset.py
  ivadomed/scripts/prepare_dataset_vertebral_labeling.py
  ivadomed/scripts/training_curve.py
  ivadomed/scripts/visualize_transforms.py
  ivadomed/utils.py
Labels: documentation, enhancement

#653 Fix missing dilate-gt.png
  ivadomed/transforms.py
Labels: bug, documentation

#607 Added warning on installation to make sure proper Python version is installed
  docs/source/installation.rst
Labels: documentation

#650 Reformat configuration_file.rst for docs
  docs/source/_static/css/custom.css
  docs/source/conf.py
  docs/source/configuration_file.rst
  ivadomed/config/config.json
  ivadomed/config/config_classification.json
  ivadomed/config/config_small.json
  ivadomed/config/config_spineGeHemis.json
  ivadomed/config/config_tumorSeg.json
  ivadomed/config/config_vertebral_labeling.json
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/main.py
  requirements.txt
Labels: documentation, refactoring

#648 New loader: BidsDataframe class
  dev/df_new_loader.py
  ivadomed/loader/utils.py
  testing/unit_tests/test_loader.py
Labels: enhancement, refactoring
