Repository ivadomed/ivadomed, pull requests merged in 2021-09, with the labels that each got.

#929 Fix link to data file in ivadomed instructions
  docs/source/usage.rst
Labels: documentation

#933 Add additional check for incorrect final_activation value
  ivadomed/models.py
Labels: bug

#897 pathlib training.py
  ivadomed/training.py
Labels: refactoring

#892 pathlib main.py
  ivadomed/main.py
Labels: refactoring

#937 Fix dropout_rate key in models.py
  docs/source/configuration_file.rst
  ivadomed/models.py
  testing/functional_tests/test_segment_volume.py
  testing/unit_tests/test_HeMIS.py
Labels: bug

#947 Pathllib for loader/bids_dataframe
  ivadomed/loader/bids_dataframe.py
Labels: refactoring

#879 pathlib for loader/utils.py
  ivadomed/loader/utils.py
Labels: refactoring

#956 Fix undo_transforms in image reconstruction
  ivadomed/inference.py
Labels: bug

#957 Fix undo_transforms in volume reconstruction
  ivadomed/inference.py
  ivadomed/testing.py
Labels: bug

#959 Update to GitHub Action to use `setup-python@v2`
  .github/workflows/pre-commit.yml
Labels: CI
