Repository ivadomed/ivadomed, pull requests merged in 2021-08, with the labels that each got.

#874 Fix segment functions for models without pre-processing transforms
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
  testing/functional_tests/test_segment_volume.py
Labels: bug

#870 Fix microscopy ground-truth range of values
  ivadomed/loader/segmentation_pair.py
  testing/unit_tests/test_loader.py
Labels: bug, enhancement

#903 fix default parameter empty list
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/scripts/visualize_and_compare_testing_models.py
  ivadomed/utils.py
  testing/unit_tests/test_postprocessing.py
Labels: refactoring

#904 Initialize the adoption of centralized management of keywords via keywords.py (Phase I: compilation of all keywords)
  ivadomed/keywords.py
Labels: refactoring

#875 change readme to point to the latest
  README.md
Labels: documentation

#880 pathlib change for object_detection/utils.py
  ivadomed/object_detection/utils.py
Labels: refactoring

#878 Pathlib adoption for loader/segmentation_pair.py
  ivadomed/loader/segmentation_pair.py
Labels: refactoring

#877 pathlib adoption for loader/film.py
  ivadomed/loader/film.py
Labels: refactoring

#881 pathlib for script/automate_training.py
  ivadomed/scripts/automate_training.py
Labels: refactoring

#886 pathlib in script/training_curve.py
  ivadomed/scripts/training_curve.py
Labels: refactoring

#883 pathlib for download_data
  ivadomed/keywords.py
  ivadomed/scripts/download_data.py
Labels: refactoring

#884 pathlib extract_small_dataset
  ivadomed/scripts/extract_small_dataset.py
Labels: refactoring

#885 pathlib in script/prepare_dataset_vertibral_labeling
  ivadomed/scripts/prepare_dataset_vertebral_labeling.py
Labels: refactoring

#887 pathlib for visualize_and_compare_testing_models.py
  ivadomed/scripts/visualize_and_compare_testing_models.py
Labels: refactoring

#888 pathlib visualize_transform
  ivadomed/scripts/visualize_transforms.py
Labels: refactoring

#889 pathlib config_manager.py
  ivadomed/config_manager.py
Labels: refactoring

#890 pathlib evaluation.py
  ivadomed/evaluation.py
Labels: refactoring

#891 pathlib inference.py
  ivadomed/inference.py
Labels: refactoring

#893 pathlib mixup.py
  ivadomed/mixup.py
Labels: refactoring

#894 pathlib models.py
  ivadomed/models.py
Labels: refactoring

#916 Fix inverted dimensions in microscopy pixelsize
  ivadomed/config/config_microscopy.json
  ivadomed/inference.py
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/segmentation_pair.py
  ivadomed/scripts/download_data.py
  testing/unit_tests/test_loader.py
Labels: bug

#895 pathlib postprocessing.py
  ivadomed/postprocessing.py
Labels: refactoring

#923 Fix training_curve.py output
  ivadomed/scripts/training_curve.py
  testing/functional_tests/test_training_curve.py
Labels: bug, enhancement

#917 Extracted BidsDataFrame class outside of loader/utils.py
  dev/df_new_loader.py
  ivadomed/loader/bids_dataframe.py
  ivadomed/loader/utils.py
  ivadomed/main.py
  ivadomed/scripts/automate_training.py
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
  testing/unit_tests/test_automate_training.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_orientation.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_testing.py
  testing/unit_tests/test_training_time.py
Labels: refactoring

#928 Extract class SliceFilter, BalancedSample and SampleMetaData from loa…
  dev/class_balance.py
  dev/metadata_config.py
  dev/plot_cluster_metadata.py
  ivadomed/inference.py
  ivadomed/loader/adaptative.py
  ivadomed/loader/balanced_sampler.py
  ivadomed/loader/loader.py
  ivadomed/loader/sample_meta_data.py
  ivadomed/loader/segmentation_pair.py
  ivadomed/loader/slice_filter.py
  ivadomed/loader/utils.py
  ivadomed/scripts/visualize_transforms.py
  ivadomed/training.py
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_transforms.py
Labels: refactoring

#851 ivadomed documentation modifications
  docs/source/installation.rst
Labels: documentation, installation
