Repository ivadomed/ivadomed, pull requests merged in 2021-03, with the labels that each got.

#691 New loader: Refactor BidsDataset classes
  dev/df_new_loader.py
  ivadomed/config/config_new_loader.json
  ivadomed/loader/adaptative_new.py
  ivadomed/loader/loader_new.py
  ivadomed/loader/utils.py
  ivadomed/object_detection/utils_new.py
  testing/unit_tests/test_loader.py
Labels: enhancement, refactoring

#700 Change archive links to repository links for pre-trained models
  docs/source/pretrained_models.rst
Labels: documentation

#721 New loader: add support for CT-scan files
  ivadomed/config/config_bids.json
  ivadomed/loader/utils.py
Labels: feature

#722 Updated .gitignore to ignore downloaded pytest data folder anywhere in repo
  .gitignore
Labels: priority:low, testing

#705 Input-level dropout feature
  docs/source/configuration_file.rst
  ivadomed/config/config_default.json
  ivadomed/loader/loader.py
  ivadomed/main.py
  testing/unit_tests/test_loader.py
Labels: feature

#725 New loader: Update test_loader.py
  ivadomed/loader/utils.py
  ivadomed/scripts/download_data.py
  testing/unit_tests/test_loader.py
Labels: testing
