Repository ivadomed/ivadomed, pull requests merged in 2021-04, with the labels that each got.

#734 New loader: Load PNG/TIF/JPG microscopy files as numpy array
  docs/source/configuration_file.rst
  ivadomed/config/config_new_loader.json
  ivadomed/loader/loader.py
  testing/unit_tests/test_loader.py
Labels: feature

#746 Remove bids_merge_dataset and bids_neuropoly
  ivadomed/loader/utils.py
  requirements.txt
Labels: installation, refactoring

#738 Refactoring: reduce complexity of BIDStoHDF5 __init__
  ivadomed/loader/adaptative.py
Labels: refactoring

#737 Refactoring: reduce complexity of BIDStoHDF5 _load_filenames
  ivadomed/config/config_spineGeHemis.json
  ivadomed/loader/adaptative.py
Labels: refactoring

#736 Refactor `create_df` in DataFrame class to reduce complexity
  ivadomed/loader/adaptative.py
Labels: refactoring

#744 Refactor and reconsolidate all test path and common utility functions with emphasis on absolute path utilization
  testing/__init__.py
  testing/common_testing_util.py
  testing/functional_tests/t_template.py
  testing/functional_tests/t_utils.py
  testing/functional_tests/test_automate_training.py
  testing/functional_tests/test_compare_models.py
  testing/functional_tests/test_convert_to_onnx.py
  testing/functional_tests/test_download_data.py
  testing/functional_tests/test_extract_small_dataset.py
  testing/functional_tests/test_prepare_dataset_vertebral_labelling.py
  testing/functional_tests/test_training_curve.py
  testing/functional_tests/test_visualize_transforms.py
  testing/unit_tests/t_template.py
  testing/unit_tests/t_utils.py
  testing/unit_tests/test_HeMIS.py
  testing/unit_tests/test_adaptative.py
  testing/unit_tests/test_automate_training.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_metrics.py
  testing/unit_tests/test_mixup.py
  testing/unit_tests/test_onnx.py
  testing/unit_tests/test_orientation.py
  testing/unit_tests/test_postprocessing.py
  testing/unit_tests/test_rgb.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_segment_volume.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_split_dataset.py
  testing/unit_tests/test_tensorboard_save.py
  testing/unit_tests/test_testing.py
  testing/unit_tests/test_training_time.py
  testing/unit_tests/test_transfer_learning.py
Labels: testing

#755 Addressing Windows Path issue causing unit test_automated_training.py unit tests to fail
  ivadomed/testing.py
Labels: bug, priority:medium

#572 visualization of multiple evaluation models
  docs/source/scripts.rst
  images/visualize_and_compare_models.png
  ivadomed/scripts/automate_training.py
  ivadomed/scripts/visualize_and_compare_testing_models.py
  requirements.txt
  setup.py
Labels: enhancement

#753 Autopublishing improvements
  .github/workflows/publish_package.yml
Labels: CI

#752 Remove data dependencies from `if` statements in the `Decoder()` forward pass
  ivadomed/models.py
Labels: deep learning, enhancement
