Repository ivadomed/ivadomed, pull requests merged in 2022-06, with the labels that each got.

#1131 Update publish_package.yml
  .github/workflows/publish_package.yml
Labels: priority:low

#1140 Drop python 3.6 to speed up CI
  .github/workflows/run_tests.yml
  setup.py
Labels: CI

#1129 unify installation (attempt #2)
  .github/workflows/pre-commit.yml
  .github/workflows/run_tests.yml
  .readthedocs.yml
  requirements.txt
  requirements_common.txt
  requirements_dev.txt
  requirements_gpu.txt
  setup.py
Labels: dependencies, installation

#1144 Revert a minor change that inhibited release
  .github/workflows/publish_package.yml
Labels: CI

#1121 Add auto disk cache capability to mri2d and mri3d dataset classes
  ivadomed/inference.py
  ivadomed/loader/bids_dataset.py
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
  ivadomed/loader/utils.py
  ivadomed/transforms.py
  ivadomed/utils.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_utils.py
Labels: enhancement, feature, priority:high, deep learning

#1127 Add syntax highlighting and improve flow of the Colab tutorials
  testing/tutorials/tutorial_1_2d_segmentation_unet.ipynb
  testing/tutorials/tutorial_3_uncertainty_estimation.ipynb
Labels: enhancement, testing, Ready for review

#1173 fix: adapt the filenames of the predictions in pred_masks as per target_suffix
  ivadomed/main.py
  ivadomed/testing.py
  testing/unit_tests/test_main.py
  testing/unit_tests/test_testing.py
Labels: bug
