Repository ivadomed/ivadomed, pull requests merged in 2022-03, with the labels that each got.

#1086 Segment with ONNX or PT model based on CPU/GPU availability
  ivadomed/models.py
  ivadomed/training.py
Labels: feature

#1109 Add type hintings to fields inside all keywords(KW) dataclasses
  ivadomed/keywords.py
Labels: enhancement

#1107 Fix loading of TIF 16bits grayscale files
  ivadomed/loader/segmentation_pair.py
  ivadomed/scripts/download_data.py
  testing/unit_tests/test_loader.py
Labels: bug

#1103 Clarify data and loading documentation
  docs/source/configuration_file.rst
  docs/source/data.rst
  docs/source/tutorials/two_class_microscopy_seg_2d_unet.rst
Labels: documentation
