Repository ivadomed/ivadomed, pull requests merged in 2022-07, with the labels that each got.

#1177 Minor correction to unsupported file extension error message
  ivadomed/loader/segmentation_pair.py
Labels: refactoring

#1174 Add description and default values to some parameters.
  docs/source/configuration_file.rst
Labels: documentation

#1145 Don't install ivadomed just to run pre-commit checks.
  .github/workflows/pre-commit.yml
Labels: CI, maintenance

#1181 Resolve imageio v2->v3 imread deprecation warnings
  ivadomed/loader/segmentation_pair.py
  requirements.txt
Labels: bug
