Repository ivadomed/ivadomed, pull requests merged in 2022-08, with the labels that each got.

#1180 Tests README: Add instructions to install testing-related packages
  testing/README.md
Labels: documentation

#1179 Remove deprecated torch and dev installation instructions
  README.md
  docs/source/installation.rst
Labels: documentation, installation

#1190 Drop testing on macOS 10
  .github/workflows/run_tests.yml
Labels: bug, testing, Ready for review, CI, maintenance

#1186 Only run tests on code changes
  .github/workflows/run_tests.yml
  .github/workflows/run_tests_dummy.yml
Labels: enhancement, testing, Ready for review, CI, maintenance

#1137 Support python3.10
  .github/workflows/run_tests.yml
  requirements.txt
  setup.py
Labels: enhancement, dependencies, installation, priority:medium
