Repository ivadomed/ivadomed, pull requests merged in 2022-04, with the labels that each got.

#1115 Drop GITHUB_TOKEN from release process
  .github/workflows/publish_package.yml
Labels: CI

#1112 Fix TSV metadata indexation and remove unused lines from bids_dataframe based on split_method
  docs/source/configuration_file.rst
  ivadomed/loader/bids_dataframe.py
  ivadomed/main.py
Labels: bug, documentation

#1100 Fix loading when names of multiple target_suffix overlap
  ivadomed/loader/bids_dataframe.py
Labels: bug
