Repository ivadomed/ivadomed, pull requests merged in 2022-09, with the labels that each got.

#1081 Fix long evaluation time on microscopy images
  docs/source/configuration_file.rst
  docs/source/tutorials/two_class_microscopy_seg_2d_unet.rst
  ivadomed/config/config_default.json
  ivadomed/config/config_microscopy.json
  ivadomed/evaluation.py
  ivadomed/main.py
  ivadomed/metrics.py
Labels: bug

#1194 chore: add an upper bound version specifier for pandas to prevent breaking the tests
  requirements.txt
Labels: bug, dependencies, CI

#1193 feat: update default args for `wandb.login()`
  ivadomed/utils.py
Labels: enhancement, feature, refactoring
