Repository ivadomed/ivadomed, pull requests merged in 2022-12, with the labels that each got.

#1209 Fix GPU behavior in segment_volume
  ivadomed/inference.py
Labels: bug

#1246 chore: remove numpy related deprecations in support of v1.24.0
  ivadomed/uncertainty.py
Labels: dependencies, CI

#1222 Fix 3D training with data augmentation
  ivadomed/keywords.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
  testing/functional_tests/test_training_3d.py
Labels: bug

#1237 fix/feat: update the path for wandb logs
  ivadomed/training.py
Labels: enhancement
