Repository ivadomed/ivadomed, pull requests merged in 2022-10, with the labels that each got.

#1185 Convert pred data to uint8 prior to imwrite png
  ivadomed/evaluation.py
  ivadomed/inference.py
Labels: Ready for review, maintenance

#1200 chore: update installation for ivadomed tutorials
  testing/tutorials/tutorial_1_2d_segmentation_unet.ipynb
  testing/tutorials/tutorial_3_uncertainty_estimation.ipynb
Labels: installation

#1196 fix: update link to contribution guidelines
  CONTRIBUTING.rst
Labels: documentation
