Repository ivadomed/ivadomed, pull requests merged in 2022-02, with the labels that each got.

#1050 Update pred_to_png prediction filenames for ADS integration
  ivadomed/evaluation.py
  ivadomed/inference.py
  ivadomed/main.py
  ivadomed/testing.py
Labels: refactoring

#980 Apply filter parameters on 2D patches to remove empty patches
  docs/source/configuration_file.rst
  ivadomed/config/config_default.json
  ivadomed/config/config_microscopy.json
  ivadomed/loader/bids_dataset.py
  ivadomed/loader/loader.py
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/patch_filter.py
  ivadomed/loader/slice_filter.py
  testing/functional_tests/test_segment_volume.py
  testing/unit_tests/test_bounding_box.py
  testing/unit_tests/test_loader.py
  testing/unit_tests/test_patch_filter.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_testing.py
  testing/unit_tests/test_training_time.py
Labels: feature

#1039 Format revamped Tutorial 1 to highlight the CLI vs JSON approaches
  docs/source/conf.py
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  requirements_dev.txt
Labels: documentation

#1037 Improve Installation Doc Readability based for Step 3 relating to GPU setup
  docs/source/installation.rst
Labels: documentation

#1063 Fixing mix-up for GPU training
  ivadomed/mixup.py
Labels: bug

#1064 Updated documentation for SoftSeg training
  docs/source/configuration_file.rst
Labels: documentation

#1040 Convert print to logger format for much more granular unified control.
  dev/class_balance.py
  dev/df_new_loader.py
  dev/filtering_lesion.py
  dev/plot_cluster_metadata.py
  dev/plot_film_parameters.py
  dev/seek_contrast_sctTesting.py
  dev/target_size.py
  ivadomed/scripts/compare_models.py
  ivadomed/scripts/download_data.py
  ivadomed/scripts/extract_small_dataset.py
  ivadomed/scripts/training_curve.py
  ivadomed/scripts/visualize_and_compare_testing_models.py
  ivadomed/scripts/visualize_transforms.py
  ivadomed/utils.py
  testing/common_testing_util.py
  testing/functional_tests/test_automate_training.py
  testing/unit_tests/test_automate_training.py
  testing/unit_tests/test_orientation.py
  testing/unit_tests/test_sampler.py
  testing/unit_tests/test_slice_filter.py
  testing/unit_tests/test_testing.py
  testing/unit_tests/test_training_time.py
  testing/unit_tests/test_transfer_learning.py
Labels: refactoring

#1045 Rewrite tutorial 2 with sphinx tab
  docs/source/tutorials/cascaded_architecture.rst
  requirements_dev.txt
Labels: documentation

#1080 Add ADS use case in documentation
  docs/source/use_cases.rst
Labels: documentation

#1085 Refactor missing print statements to be using logger
  testing/unit_tests/test_patch_filter.py
Labels: refactoring

#1025 Update microscopy following BEP release
  ivadomed/config/config_bids.json
  ivadomed/inference.py
  ivadomed/keywords.py
  ivadomed/loader/bids_dataframe.py
  ivadomed/loader/segmentation_pair.py
  ivadomed/main.py
  ivadomed/scripts/download_data.py
  testing/unit_tests/test_loader.py
Labels: enhancement

#994 Update pybids to 0.14.0
  ivadomed/loader/bids_dataframe.py
  requirements_common.txt
Labels: refactoring
