Repository ivadomed/ivadomed, pull requests merged in 2023-01, with the labels that each got.

#1244 Clarify testing output files
  docs/source/tutorials/one_class_segmentation_2d_unet.rst
  docs/source/tutorials/two_class_microscopy_seg_2d_unet.rst
  ivadomed/evaluation.py
Labels: documentation, refactoring

#1265 Clarify usage of --no-patch for 2D only
  docs/source/usage.rst
  ivadomed/inference.py
Labels: documentation, refactoring

#1254 Introduce `segment_image` CLI
  docs/source/scripts.rst
  ivadomed/scripts/segment_image.py
  setup.py
Labels: feature

#1267 Fix NormalizeInstance for uniform samples
  ivadomed/transforms.py
  testing/unit_tests/test_transforms.py
Labels: bug

#1266 Harmonize get_item in MRI2D dataset and MRI3D dataset
  ivadomed/keywords.py
  ivadomed/loader/mri2d_segmentation_dataset.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
Labels: refactoring

#1164 `PatchFilter` for 3D subvolume filtering
  docs/source/configuration_file.rst
  ivadomed/loader/bids3d_dataset.py
  ivadomed/loader/loader.py
  ivadomed/loader/mri3d_subvolume_segmentation_dataset.py
  ivadomed/loader/patch_filter.py
  testing/unit_tests/test_patch_filter.py
Labels: feature, Ready for review, priority:high

#1271 Resolve the discrepancies
  docs/source/configuration_file.rst
Labels: documentation

#1281 Point to the URL specific to the learning rate
  docs/source/configuration_file.rst
Labels: documentation

#1278 Match location of `object_detection` in the template config file and in the documentation
  docs/source/configuration_file.rst
  ivadomed/config/config.json
Labels: documentation
